# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dEC1bPtLl5sYkGvN0DIB2s2j5EP0Wf9H
"""

import streamlit as st
st.markdown("""
<style>
body {
    background: linear-gradient(135deg, #0f172a, #1e293b);
}
</style>
""", unsafe_allow_html=True)

import base64

def get_video_base64(path):
    with open(path, "rb") as video_file:
        return base64.b64encode(video_file.read()).decode()

video_base64 = get_video_base64("bg2.mp4")

st.markdown("""
<style>
video {
    position: fixed;
    right: 0;
    bottom: 0;
    min-width: 100%;
    min-height: 100%;
    z-index: -1;
    object-fit: cover;
    opacity: 0.6;
}
</style>

<video autoplay muted loop>
  <source src="https://res.cloudinary.com/dbv8sjwrz/video/upload/v1775218605/bg2_q4l63g.mp4" type="video/mp4">
</video>
""", unsafe_allow_html=True)

import joblib
import re
import nltk

nltk.download('stopwords')
nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('wordnet')

from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize

# Load saved models
model = joblib.load("toxicity_model.pkl")
vectorizer = joblib.load("tfidf_vectorizer.pkl")
label_encoder = joblib.load("label_encoder.pkl")

# NLP tools
stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

def preprocess_text(text):

    text = text.lower()
    text = re.sub(r"http\S+|www\S+|https\S+", '', text)
    text = re.sub(r'<.*?>', '', text)
    text = re.sub(r'\d+', '', text)
    text = re.sub(r'[^\w\s]', '', text)

    tokens = word_tokenize(text)

    tokens = [word for word in tokens if word not in stop_words]

    tokens = [lemmatizer.lemmatize(word) for word in tokens]

    return " ".join(tokens)

# Streamlit UI
st.markdown("<h1 style='text-align:center;color:#00ffff;'>🚨 Hate Speech Detection System</h1>", unsafe_allow_html=True)

st.write("Enter a comment below to analyze toxicity.")

user_input = st.text_area("Comment")

if st.button("Analyze Comment"):

    if user_input.strip() == "":
        st.warning("Please enter a comment.")
    else:

        cleaned = preprocess_text(user_input)

        vector = vectorizer.transform([cleaned])

        prediction = model.predict(vector)

        prediction_label = label_encoder.inverse_transform(prediction)[0]

        # Get confidence score
        prob = model.predict_proba(vector)

        confidence = prob.max() * 100

        st.subheader("Detection Result")

        st.write("Predicted Category:", prediction_label)

        st.write("Confidence Score:", f"{confidence:.2f}%")

        if prediction_label == "non_toxic":
            st.markdown(f"""
            <div style="background-color:rgba(0,255,0,0.2);padding:15px;border-radius:10px">
            ✅ SAFE COMMENT<br>
            Confidence: {confidence:.2f}%
            </div>
            """, unsafe_allow_html=True)
        else:
            st.markdown(f"""
            <div style="background-color:rgba(255,0,0,0.3);padding:15px;border-radius:10px">
            🚨 TOXIC CONTENT DETECTED<br>
            Category: {prediction_label}<br>
            Confidence: {confidence:.2f}%
            </div>
            """, unsafe_allow_html=True)

